version: '3'
services:
  postgres:
    image: postgres:12.5
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.2
    ports:
      - 6379:6379
    command: redis-server --appendonly yes
    volumes:
      - ./.redis_data:/data
